name: calendar_view
description: A Flutter package allows you to easily implement all calendar UI and calendar event functionality.
version: 1.2.1

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  linked_scroll_controller: ^0.2.0

dev_dependencies:
  lints:
  flutter_test:
    sdk: flutter

flutter:
